version: 2.0
jobs:
  build:
    docker:
      - image: circleci/node:10
    branches:
      only:
          - main
    steps:
      - add_ssh_keys:
          fingerprints:
            - "9a:a7:0b:34:da:1b:86:0b:d6:04:db:ca:f1:1d:26:21"
      - checkout
      - run:
          name:Install
          command:yarn install
      - run:
          name:Build
          command:yarn build
