version: 2.0
jobs:
  build:
    docker:
      - image: circleci/node:10
    branches:
      only:
          - main
    steps:
      - add_ssh_keys:
          fingerprints:
            - "9a:a7:0b:34:da:1b:86:0b:d6:04:db:ca:f1:1d:26:21"
      - checkout
      - restore_cache:
          keys:
              - dependencies_imooc
      - run:
          name: Install
          command: yarn install
      - save_cache:
          paths:
            - node_modules
          key: dependencies_imooc
      - run:
          name: Build
          command: yarn build
      - run:
          name: Deploy
          command: chmod -X scripts/deploy.sh
      - run:
          name: Run Deploy to Github pages
          command: ./scripts/deploy.sh
